# Copyright (c) 2023-2024 AlertAvert.com
# All rights reserved.
# Created by Marco Massenzio, 2023-07-13

name: Majordomo
version: 0.5.0
description: An LLM-powered code-generation assistant for expert developers
author: Marco Massenzio (marco@alertavert.com)
license: Proprietary
url: https://alertavert.com/majordomo
